/*
 * InfoPanel.java
 *
 * Created on 14. Januar 2007, 23:43
 */

package pagerank.visualization;

/**
 *
 * @author  Thomas
 */
public class InfoPanel extends javax.swing.JPanel
{
  
  /** Creates new form InfoPanel */
  public InfoPanel()
  {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    lblURL = new javax.swing.JLabel();
    lblPageRank = new javax.swing.JLabel();
    txtURL = new javax.swing.JTextField();

    setBackground(new java.awt.Color(255, 255, 102));
    lblURL.setFont(new java.awt.Font("Dialog", 0, 12));
    lblURL.setText("URL: ");

    lblPageRank.setFont(new java.awt.Font("Dialog", 0, 12));
    lblPageRank.setText("PageRank: ");

    txtURL.setBackground(new java.awt.Color(255, 255, 102));
    txtURL.setEditable(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lblPageRank, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(lblURL)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblURL)
          .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPageRank)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
 
 public void setURL(String url)
 {
   txtURL.setText(url);
 }
 
 public void setPageRank(String str)
 {
   lblPageRank.setText("PageRank: " + str);
 }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lblPageRank;
  private javax.swing.JLabel lblURL;
  private javax.swing.JTextField txtURL;
  // End of variables declaration//GEN-END:variables
  
}
