/*
 * InfoDialog.java
 *
 * Created on 10. Februar 2007, 18:22
 */

package pagerank.visualization;

/**
 *
 * @author  thomas
 */
public class InfoDialog extends javax.swing.JDialog
{
  
  /** Creates new form InfoDialog */
  public InfoDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Zanysson Info");
    jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
    jLabel1.setText("Zanysson");

    jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel2.setText("<html>&copy; 2007 by Alexandra Danilkina, Fabian Fier and Thomas Krause</html>");

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel3.setText("version 1");

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel4.setText("<html>Developed as a project inside the course \"Qualitative und quantitative Analyse von Texten\", a collaboration between the institute of linguistics and the institute of computer science at Humboldt University of Berlin.</html>");
    jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    jButton1.setFont(new java.awt.Font("Dialog", 0, 12));
    jButton1.setMnemonic('c');
    jButton1.setText("Close");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onCloseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addContainerGap())
    );
    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-445)/2, (screenSize.height-182)/2, 445, 182);
  }// </editor-fold>//GEN-END:initComponents

  private void onCloseClicked(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCloseClicked
  {//GEN-HEADEREND:event_onCloseClicked
    this.setVisible(false);
  }//GEN-LAST:event_onCloseClicked
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new InfoDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  // End of variables declaration//GEN-END:variables
  
}
